groups:
- name: /tmp/prometheus.alerts
  rules:
  - alert: PrometheusScrapeError
    expr: up == 0
    for: 45m
    labels:
      monitored_item: '{{$labels.bosh_deployment}}/{{$labels.bosh_job_name}}'
      service: prometheus
      severity: warning
      spark: "false"
    annotations:
      description: The Prometheus instance at `{{$labels.instance}}` for scrape job
        `{{$labels.job}}` has been down or has not been reachable during the last
        45m
      summary: Prometheus instance `{{$labels.instance}}` (scrape job `{{$labels.job}}`)
        down or not reachable
  - alert: PrometheusConfigReloadFailed
    expr: prometheus_config_last_reload_successful == 0
    for: 15m
    labels:
      monitored_item: '{{$labels.bosh_deployment}}/{{$labels.bosh_job_name}}'
      service: prometheus
      severity: warning
      spark: "false"
    annotations:
      description: The Prometheus instance at `{{$labels.instance}}` has failed to
        reload its configuration during the last 15m
      summary: Prometheus instance `{{$labels.instance}}` config reload failed
  - alert: PrometheusSkippingScrapes
    expr: rate(prometheus_target_skipped_scrapes_total[10m]) > 1
    for: 10m
    labels:
      monitored_item: '{{$labels.bosh_deployment}}/{{$labels.bosh_job_name}}'
      service: prometheus
      severity: warning
      spark: "false"
    annotations:
      description: The Prometheus instance at `{{$labels.instance}}` has been skipping
        scrapes during the last 10m
      summary: Prometheus instance `{{$labels.instance}}` is skipping scrapes
  - alert: PrometheusExceededSampleLimit
    expr: rate(prometheus_target_scrapes_exceeded_sample_limit_total[10m]) > 1
    for: 10m
    labels:
      monitored_item: '{{$labels.bosh_deployment}}/{{$labels.bosh_job_name}}'
      service: prometheus
      severity: warning
      spark: "false"
    annotations:
      description: The Prometheus instance at `{{$labels.instance}}` exceeded the
        sample limit during the last 10m
      summary: Prometheus instance `{{$labels.instance}}` exceeded the sample limit
  - alert: PrometheusNotificationsDroppedTooHigh
    expr: rate(prometheus_notifications_dropped_total[10m]) > 1
    for: 10m
    labels:
      monitored_item: '{{$labels.bosh_deployment}}/{{$labels.bosh_job_name}}'
      service: prometheus
      severity: warning
      spark: "false"
    annotations:
      description: The Prometheus instance at `{{$labels.instance}}` has been dropping
        to much notifications during the last 10m
      summary: Prometheus instance `{{$labels.instance}}` is dropping notifications
  - alert: PrometheusNotificationsQueueTooHigh
    expr: rate(prometheus_notifications_queue_length[10m]) > 1
    for: 30m
    labels:
      monitored_item: '{{$labels.bosh_deployment}}/{{$labels.bosh_job_name}}'
      service: prometheus
      severity: warning
      spark: "false"
    annotations:
      description: The Prometheus instance at `{{$labels.instance}}` notifications
        queue has been too high during the last 30m
      summary: Prometheus instance `{{$labels.instance}}` notifications queue is too
        high
